
# 主要用于pychram
DOMAIN-SUFFIX,jetbrains.ai
DOMAIN-SUFFIX,jetbrains.com
DOMAIN-SUFFIX,augmentcode.com

# 金融类
DOMAIN-SUFFIX,reddit.com
DOMAIN-SUFFIX,facebook.com
DOMAIN-SUFFIX,x.com
DOMAIN-SUFFIX,instagram.com
DOMAIN-SUFFIX,spotify.com
DOMAIN-SUFFIX,okx.com
DOMAIN-SUFFIX,binance.com
DOMAIN-SUFFIX,changenow.io
DOMAIN-SUFFIX,mexc.com
