# EE / CMLinkUK
IP-CIDR,46.68.0.0/17,no-resolve
# Giffgaff
IP-CIDR,87.194.0.0/16,no-resolve
# CTE
IP-CIDR,31.94.0.0/16,no-resolve
# Vodafone / VOXI
IP-CIDR,88.82.0.0/19,no-resolve
IP-CIDR,148.252.160.0/19,no-resolve
# T-Mobile US
IP-CIDR,208.54.0.0/16,no-resolve
IP-CIDR,66.94.0.0/19,no-resolve
IP-CIDR,206.29.177.36/32,no-resolve
