# T-Mobile US
DOMAIN-SUFFIX,crl.t-mobile.com
DOMAIN-SUFFIX,eas3.msg.t-mobile.com
DOMAIN-SUFFIX,mascns.t-mobile.com
DOMAIN-SUFFIX,ns.sipgeo.t-mobile.com
DOMAIN-SUFFIX,epdg.epc.mnc240.mcc310.pub.3gppnetwork.org
DOMAIN-SUFFIX,epdg.epc.mnc260.mcc310.pub.3gppnetwork.org
DOMAIN-SUFFIX,ss.epdg.epc.mnc260.mcc310.pub.3gppnetwork.org
DOMAIN-SUFFIX,ss.epdg.epc.geo.mnc260.mcc310.pub.3gppnetwork.org
# CSL / HK
DOMAIN-SUFFIX,csl.prod.ondemandconnectivity.com
DOMAIN-SUFFIX,hhk.prod.ondemandconnectivity.com
DOMAIN-SUFFIX,epdg.epc.mnc000.mcc454.pub.3gppnetwork.org
DOMAIN-SUFFIX,ss.epdg.epc.mnc000.mcc454.pub.3gppnetwork.org
DOMAIN-SUFFIX,ss.epdg.epc.geo.mnc000.mcc454.pub.3gppnetwork.org
# NZ
DOMAIN-SUFFIX,epdg.epc.mnc001.mcc530.pub.3gppnetwork.org
# Apple 地区检测
DOMAIN-SUFFIX,gspe1-ssl.ls.apple.com
# 沃达丰
DOMAIN-SUFFIX,epdg.epc.mnc015.mcc234.pub.3gppnetwork.org
DOMAIN-SUFFIX,ss.epdg.epc.mnc015.mcc234.pub.3gppnetwork.org
DOMAIN-SUFFIX,ss.epdg.epc.geo.mnc015.mcc234.pub.3gppnetwork.org
DOMAIN-SUFFIX,entsrv-uk.vodafone.com
DOMAIN-SUFFIX,vuk-gto.prod.ondemandconnectivity.com
# VOXI
DOMAIN,vfgb.idemia.io
# mcc234 关键词
DOMAIN-KEYWORD,mcc234
# EE / CTE
DOMAIN-SUFFIX,ct.ee.co.uk
